name: Daily Spider

on:
  schedule:
    - cron: "0 13 * * *"   # 每天 UTC 13:00
  workflow_dispatch:

jobs:
  run-spider:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run spider
        run: |
          python adzuna.py

      - name: Commit new files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add *.csv
          git commit -m "Add daily data"
          git push
